### ISSUE TITLE
duvida

### ISSUE THREAD

**Issue by thiago5171** [laiananardi/100daysofcode#83]
ola, achei muito legal o design do seu README.md , gostaria de saber se vc poderia me orientar algum canal ou site que ensine a deixar com visual mais intuitivo, estou começando a usar o github faz pouco tempo, entao sou meio leigo ainda.

**Comment by joevtap** [comment]
> 
> 
> ola, achei muito legal o design do seu README.md , gostaria de saber se vc poderia me orientar algum canal ou site que ensine a deixar com visual mais intuitivo, estou começando a usar o github faz pouco tempo, entao sou meio leigo ainda.


Oi Thiago, tudo bom? Eu não sou a Lai, mas acho que consigo te ajudar um pouco :D

Os arquivos README.md são escritos usando uma linguagem de marcação chamada Markdown, é uma linguagem de marcação como o HTML mas um pouquinho mais simples de usar. Para escrever esses arquivos README, você precisa aprender primeiro a sintaxe do Markdown (MD para os íntimos), aqui no próprio Github tem uma [Cheatsheet de MD](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) que você pode usar para aprender.

Mesmo assim, tem algumas coisas que são meio chatas de fazer na mão e, por isso, pessoas muito sagazes desenvolveram ferramentas muito úteis pra facilitar a vida de muita gente.

___

# Ferramentas úteis que vão te ajudar a escrever READMEs surreais
- [Markdown Tables Generator](https://www.tablesgenerator.com/markdown_tables), um gerador de tabelas em MD
- [StackEdit Markdown Editor](https://stackedit.io/), um editor MD para o browser
- [ScreenToGif](https://www.screentogif.com/), um gravador de tela que exporta a gravação em GIF (que pode ser usado com MD)
- [Emojipedia.org](https://emojipedia.org/), uma biblioteca de emojis pra copiar e colar nos seus READMEs (Sim, você pode usar emojis em MD files 😃)
- [Shields.io](https://shields.io/), uma Webapp para gerar badges para READMEs
- [Make a README](https://www.makeareadme.com/), template de README juntamente com dicas para fazer READMEs surreais

___

São essas as dicas que eu tenho pra te dar, espero que elas te ajudem a fazer READMEs sensacionais para acompanhar seus projetos também sensacionais :D

**Comment by thiago5171** [comment]
cara muito obrigado
